export const FETCH_GROUPS_REQUEST = 'groups/FETCH_GROUPS_REQUEST';
export const FETCH_GROUPS_SUCCESS = 'groups/FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_FAILURE = 'groups/FETCH_GROUPS_FAILURE';

export const FETCH_GROUP_REQUEST = 'groups/FETCH_GROUP_REQUEST';
export const FETCH_GROUP_SUCCESS = 'groups/FETCH_GROUP_SUCCESS';
export const FETCH_GROUP_FAILURE = 'groups/FETCH_GROUP_FAILURE';

export const EDIT_GROUP_REQUEST = 'groups/EDIT_GROUP_REQUEST';
export const EDIT_GROUP_SUCCESS = 'groups/EDIT_GROUP_SUCCESS';
export const EDIT_GROUP_FAILURE = 'groups/EDIT_GROUP_FAILURE';

export const ADD_MEMBERS_REQUEST = 'groups/ADD_MEMBERS_REQUEST';
export const ADD_MEMBERS_SUCCESS = 'groups/ADD_MEMBERS_SUCCESS';
export const ADD_MEMBERS_FAILURE = 'groups/ADD_MEMBERS_FAILURE';

export const DELETE_MEMBERS_REQUEST = 'groups/DELETE_MEMBERS_REQUEST';
export const DELETE_MEMBERS_SUCCESS = 'groups/DELETE_MEMBERS_SUCCESS';
export const DELETE_MEMBERS_FAILURE = 'groups/DELETE_MEMBERS_FAILURE';

export const CREATE_GROUP_REQUEST = 'groups/CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'groups/CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'groups/CREATE_GROUP_FAILURE';

export const DELETE_GROUP_REQUEST = 'groups/DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'groups/DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILURE = 'groups/DELETE_GROUP_FAILURE';
