export const FETCH_INTERESTINGTOKNOW_REQUEST =
  "employee/interestingToKnow/FETCH_INTERESTINGTOKNOW_REQUEST";
export const FETCH_INTERESTINGTOKNOW_SUCCESS =
  "employee/interestingToKnow/FETCH_INTERESTINGTOKNOW_SUCCESS";
export const FETCH_INTERESTINGTOKNOW_FAILURE =
  "employee/interestingToKnow/FETCH_INTERESTINGTOKNOW_FAILURE";
export const FETCH_CURRENT_INTERESTINGTOKNOW_REQUEST =
  "employee/interestingToKnow/FETCH_CURRENT_INTERESTINGTOKNOW_REQUEST";
export const FETCH_CURRENT_INTERESTINGTOKNOW_SUCCESS =
  "employee/interestingToKnow/FETCH_CURRENT_INTERESTINGTOKNOW_SUCCESS";
export const FETCH_CURRENT_INTERESTINGTOKNOW_FAILURE =
  "employee/interestingToKnow/FETCH_CURRENT_INTERESTINGTOKNOW_FAILURE";
export const CLEAR_CURRENT_INTERESTINGTOKNOW =
  "employee/interestingToKnow/CLEAR_CURRENT_INTERESTINGTOKNOW";
export const CREATE_INTERESTINGTOKNOW_REQUEST =
  "employee/interestingToKnow/CREATE_INTERESTINGTOKNOW_REQUEST";
export const CREATE_INTERESTINGTOKNOW_SUCCESS =
  "employee/interestingToKnow/CREATE_INTERESTINGTOKNOW_SUCCESS";
export const CREATE_INTERESTINGTOKNOW_FAILURE =
  "employee/interestingToKnow/CREATE_INTERESTINGTOKNOW_FAILURE";
export const UPDATE_INTERESTINGTOKNOW_REQUEST =
  "employee/interestingToKnow/UPDATE_INTERESTINGTOKNOW_REQUEST";
export const UPDATE_INTERESTINGTOKNOW_SUCCESS =
  "employee/interestingToKnow/UPDATE_INTERESTINGTOKNOW_SUCCESS";
export const UPDATE_INTERESTINGTOKNOW_FAILURE =
  "employee/interestingToKnow/UPDATE_INTERESTINGTOKNOW_FAILURE";
export const DELETE_INTERESTINGTOKNOW_REQUEST =
  "employee/interestingToKnow/DELETE_INTERESTINGTOKNOW_REQUEST";
export const DELETE_INTERESTINGTOKNOW_SUCCESS =
  "employee/interestingToKnow/DELETE_INTERESTINGTOKNOW_SUCCESS";
export const DELETE_INTERESTINGTOKNOW_FAILURE =
  "employee/interestingToKnow/DELETE_INTERESTINGTOKNOW_FAILURE";
export const UPLOAD_INTERESTINGTOKNOW_PHOTO_REQUEST =
  "employee/interestingToKnow/UPLOAD_INTERESTINGTOKNOW_PHOTO_REQUEST";
export const UPLOAD_INTERESTINGTOKNOW_PHOTO_SUCCESS =
  "employee/interestingToKnow/UPLOAD_INTERESTINGTOKNOW_PHOTO_SUCCESS";
export const UPLOAD_INTERESTINGTOKNOW_PHOTO_FAILURE =
  "employee/interestingToKnow/UPLOAD_INTERESTINGTOKNOW_PHOTO_FAILURE";
