export const FETCH_EVENTS_REQUEST = 'events/FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'events/FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'events/FETCH_EVENTS_FAILURE';

export const CREATE_EVENTS_REQUEST = 'events/CREATE_EVENTS_REQUEST';
export const CREATE_EVENTS_SUCCESS = 'events/CREATE_EVENTS_SUCCESS';
export const CREATE_EVENTS_FAILURE = 'events/CREATE_EVENTS_FAILURE';

export const FETCH_EVENT_REQUEST = 'eventa/FETCH_EVENT_REQUEST';
export const FETCH_EVENT_SUCCESS = 'eventa/FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILURE = 'eventa/FETCH_EVENT_FAILURE';

// export const EDIT_GROUP_REQUEST = 'groups/EDIT_GROUP_REQUEST';
// export const EDIT_GROUP_SUCCESS = 'groups/EDIT_GROUP_SUCCESS';
// export const EDIT_GROUP_FAILURE = 'groups/EDIT_GROUP_FAILURE';

// export const ADD_MEMBERS_REQUEST = 'groups/ADD_MEMBERS_REQUEST';
// export const ADD_MEMBERS_SUCCESS = 'groups/ADD_MEMBERS_SUCCESS';
// export const ADD_MEMBERS_FAILURE = 'groups/ADD_MEMBERS_FAILURE';

// export const DELETE_MEMBERS_REQUEST = 'groups/DELETE_MEMBERS_REQUEST';
// export const DELETE_MEMBERS_SUCCESS = 'groups/DELETE_MEMBERS_SUCCESS';
// export const DELETE_MEMBERS_FAILURE = 'groups/DELETE_MEMBERS_FAILURE';

// export const DELETE_GROUP_REQUEST = 'groups/DELETE_GROUP_REQUEST';
// export const DELETE_GROUP_SUCCESS = 'groups/DELETE_GROUP_SUCCESS';
// export const DELETE_GROUP_FAILURE = 'groups/DELETE_GROUP_FAILURE';
